### ISSUE TITLE
Is this project active?

### ISSUE THREAD

**Issue by ghost** [pawanpaudel93/Torrent2drive#2]
Hi all.

I want to help, but I want to know if this project is active. *Is this project active?*

**Comment by pawanpaudel93** [comment]
@codehangen It's not active. It was updated and moved here https://github.com/pawanpaudel93/Torrent2GDrive

**Comment by ghost** [comment]
Hi pawanpaudel93.

> @codehangen It's not active. It was updated and moved here https://github.com/pawanpaudel93/Torrent2GDrive

thank you for feedback.
